from typing import Any


COMMON_PIZZA_MODIFIERS: dict[str, Any] = {
    "sizes": {"standard": 0, "familj": 24000},
    "crusts": {"glutenfri": 3000},
    "toppings": {
        "extra cheese": 2500,
        "ham": 2500,
        "mushrooms": 1500,
        "onion": 1000,
        "pineapple": 1500,
        "shrimp": 3500,
        "kebab meat": 3500,
        "chicken": 3000,
        "jalapeno": 1500,
        "olives": 1500,
        "bearnaise sauce": 1500,
        "garlic sauce": 1500,
        "kebab sauce": 1500,
        "no onion": 0,
    },
    "half_and_half": True,
}


SWEDISH_PIZZA_MENU: list[dict[str, Any]] = [
    {
        "name": "Margherita",
        "category": "Standardpizzor",
        "base_price": 12000,
        "description": "Tomatsås och ost.",
        "allergens": ["gluten", "milk"],
        "modifiers": COMMON_PIZZA_MODIFIERS,
        "sort_order": 10,
    },
    {
        "name": "Vesuvio",
        "category": "Standardpizzor",
        "base_price": 12000,
        "description": "Tomatsås, ost och skinka.",
        "allergens": ["gluten", "milk"],
        "modifiers": COMMON_PIZZA_MODIFIERS,
        "sort_order": 20,
    },
    {
        "name": "Calzone",
        "category": "Standardpizzor",
        "base_price": 12000,
        "description": "Inbakad pizza med tomatsås, ost och skinka.",
        "allergens": ["gluten", "milk"],
        "modifiers": {**COMMON_PIZZA_MODIFIERS, "half_and_half": False},
        "sort_order": 30,
    },
    {
        "name": "Hawaii",
        "category": "Standardpizzor",
        "base_price": 12000,
        "description": "Tomatsås, ost, skinka och ananas.",
        "allergens": ["gluten", "milk"],
        "modifiers": COMMON_PIZZA_MODIFIERS,
        "sort_order": 40,
    },
    {
        "name": "Capricciosa",
        "category": "Standardpizzor",
        "base_price": 12000,
        "description": "Tomatsås, ost, skinka och champinjoner.",
        "allergens": ["gluten", "milk"],
        "modifiers": COMMON_PIZZA_MODIFIERS,
        "sort_order": 50,
    },
    {
        "name": "Funghi",
        "category": "Standardpizzor",
        "base_price": 12000,
        "description": "Tomatsås, ost och champinjoner.",
        "allergens": ["gluten", "milk"],
        "modifiers": COMMON_PIZZA_MODIFIERS,
        "sort_order": 60,
    },
    {
        "name": "Bolognese",
        "category": "Standardpizzor",
        "base_price": 12000,
        "description": "Tomatsås, ost och köttfärssås.",
        "allergens": ["gluten", "milk"],
        "modifiers": COMMON_PIZZA_MODIFIERS,
        "sort_order": 70,
    },
    {
        "name": "Pescatore",
        "category": "Standardpizzor",
        "base_price": 12000,
        "description": "Tomatsås, ost, tonfisk och lök.",
        "allergens": ["gluten", "milk", "fish"],
        "modifiers": COMMON_PIZZA_MODIFIERS,
        "sort_order": 80,
    },
    {
        "name": "Cacciatore",
        "category": "Standardpizzor",
        "base_price": 13000,
        "description": "Tomatsås, ost, salami, champinjoner och lök.",
        "allergens": ["gluten", "milk"],
        "modifiers": COMMON_PIZZA_MODIFIERS,
        "sort_order": 90,
    },
    {
        "name": "Marinara",
        "category": "Standardpizzor",
        "base_price": 13000,
        "description": "Tomatsås, ost, räkor och musslor.",
        "allergens": ["gluten", "milk", "shellfish", "molluscs"],
        "modifiers": COMMON_PIZZA_MODIFIERS,
        "sort_order": 100,
    },
    {
        "name": "Vegetaria",
        "category": "Standardpizzor",
        "base_price": 13000,
        "description": "Tomatsås, ost, champinjoner, paprika, kronärtskocka och lök.",
        "allergens": ["gluten", "milk"],
        "modifiers": {**COMMON_PIZZA_MODIFIERS, "toppings": {**COMMON_PIZZA_MODIFIERS["toppings"], "vegan cheese": 1000}},
        "sort_order": 110,
    },
    {
        "name": "Quattro Stagioni",
        "category": "Specialpizzor",
        "base_price": 14000,
        "description": "Tomatsås, ost, skinka, champinjoner, räkor, musslor och paprika.",
        "allergens": ["gluten", "milk", "shellfish", "molluscs"],
        "modifiers": COMMON_PIZZA_MODIFIERS,
        "sort_order": 120,
    },
    {
        "name": "Milano",
        "category": "Specialpizzor",
        "base_price": 14000,
        "description": "Tomatsås, ost, räkor, bacon, tonfisk och champinjoner.",
        "allergens": ["gluten", "milk", "fish", "shellfish"],
        "modifiers": COMMON_PIZZA_MODIFIERS,
        "sort_order": 130,
    },
    {
        "name": "Apollo",
        "category": "Specialpizzor",
        "base_price": 14000,
        "description": "Tomatsås, ost, salami, champinjoner, paprika, gröna oliver och lök.",
        "allergens": ["gluten", "milk"],
        "modifiers": COMMON_PIZZA_MODIFIERS,
        "sort_order": 140,
    },
    {
        "name": "Kebabpizza",
        "category": "Kebabpizzor",
        "base_price": 14500,
        "description": "Tomatsås, ost, kebabkött, champinjoner, lök, feferoni och kebabsås.",
        "allergens": ["gluten", "milk"],
        "modifiers": {
            **COMMON_PIZZA_MODIFIERS,
            "sizes": {"standard": 0, "familj": 26000},
            "sauces": {"kebabsås": 0, "vitlökssås": 0, "stark sås": 0, "sås bredvid": 0},
        },
        "sort_order": 150,
    },
    {
        "name": "Kebabpizza Special",
        "category": "Kebabpizzor",
        "base_price": 16500,
        "description": "Tomatsås, ost, kebabkött, pommes, sallad, lök, feferoni och valfri sås.",
        "allergens": ["gluten", "milk"],
        "modifiers": {
            **COMMON_PIZZA_MODIFIERS,
            "sizes": {"standard": 0, "familj": 28000},
            "sauces": {"kebabsås": 0, "vitlökssås": 0, "stark sås": 0, "sås bredvid": 0},
        },
        "sort_order": 160,
    },
    {
        "name": "Vegan Kebabpizza",
        "category": "Kebabpizzor",
        "base_price": 15500,
        "description": "Tomatsås, vegansk ost, vegankebab, ananas, champinjoner, paprika, oliver och lök.",
        "allergens": ["gluten"],
        "modifiers": {
            **COMMON_PIZZA_MODIFIERS,
            "sizes": {"standard": 0, "familj": 27000},
            "toppings": {**COMMON_PIZZA_MODIFIERS["toppings"], "vegan cheese": 1000, "extra vegan kebab": 3000},
        },
        "sort_order": 170,
    },
    {
        "name": "Pepperoni Pizza",
        "category": "Premium pizzor",
        "base_price": 14900,
        "description": "Tomatsås, mozzarella och pepperonikorv.",
        "allergens": ["gluten", "milk"],
        "modifiers": {**COMMON_PIZZA_MODIFIERS, "sizes": {"medium": 0, "large": 2000}},
        "sort_order": 180,
    },
    {
        "name": "BBQ Chicken",
        "category": "Premium pizzor",
        "base_price": 15900,
        "description": "Tomatsås, mozzarella, kyckling, paprika, lök och BBQ-sås.",
        "allergens": ["gluten", "milk"],
        "modifiers": {**COMMON_PIZZA_MODIFIERS, "sizes": {"medium": 0, "large": 2000}},
        "sort_order": 190,
    },
    {
        "name": "The Vegetarian",
        "category": "Premium pizzor",
        "base_price": 16500,
        "description": "Tomatsås, mozzarella, portabello, zucchini, paprika, oliver, grönkål och persiljeolja.",
        "allergens": ["gluten", "milk"],
        "modifiers": {**COMMON_PIZZA_MODIFIERS, "sizes": {"medium": 0, "large": 2000}},
        "sort_order": 200,
    },
    {
        "name": "Kebabtallrik",
        "category": "Kebab och grill",
        "base_price": 12500,
        "description": "Kebabkött med pommes eller ris, sallad, tomat, lök, feferoni och valfri sås.",
        "allergens": ["milk"],
        "modifiers": {"sides": {"pommes": 0, "ris": 0}, "sauces": {"kebabsås": 0, "vitlökssås": 0, "stark sås": 0}},
        "sort_order": 210,
    },
    {
        "name": "Kebabrulle",
        "category": "Kebab och grill",
        "base_price": 12500,
        "description": "Tunnbröd med kebabkött, sallad, tomat, lök, feferoni och valfri sås.",
        "allergens": ["gluten", "milk"],
        "modifiers": {"sauces": {"kebabsås": 0, "vitlökssås": 0, "stark sås": 0}, "toppings": {"extra kebab": 3000, "feta cheese": 2000}},
        "sort_order": 220,
    },
    {
        "name": "Vitlöksbröd",
        "category": "Tillbehör",
        "base_price": 4900,
        "description": "Ugnsbakat bröd med vitlökssmör.",
        "allergens": ["gluten", "milk"],
        "modifiers": {"toppings": {"extra cheese": 1500}},
        "sort_order": 230,
    },
    {
        "name": "Pizzasallad liten",
        "category": "Tillbehör",
        "base_price": 2000,
        "description": "Klassisk svensk pizzasallad med vitkål.",
        "allergens": [],
        "modifiers": {},
        "sort_order": 240,
    },
    {
        "name": "Pizzasallad stor",
        "category": "Tillbehör",
        "base_price": 3000,
        "description": "Stor pizzasallad med vitkål.",
        "allergens": [],
        "modifiers": {},
        "sort_order": 250,
    },
    {
        "name": "Läsk 33cl",
        "category": "Dryck",
        "base_price": 2000,
        "description": "Coca-Cola, Fanta, Sprite eller mineralvatten 33 cl.",
        "allergens": [],
        "modifiers": {"flavors": {"Coca-Cola": 0, "Fanta": 0, "Sprite": 0, "mineralvatten": 0}},
        "sort_order": 260,
    },
    {
        "name": "Läsk 1.5L",
        "category": "Dryck",
        "base_price": 5000,
        "description": "Coca-Cola, Fanta eller Sprite 1.5 liter.",
        "allergens": [],
        "modifiers": {"flavors": {"Coca-Cola": 0, "Fanta": 0, "Sprite": 0}},
        "sort_order": 270,
    },
]
